export const Strings = {
  appTitle: 'SAYISAL\nZEKA OYUNU',
  appSubtitle: 'BULLS & COWS',
  startScreen: {
    play: 'OYUNA BASLA',
    description: 'Rastgele bir rakip ile 4 haneli\ngizli sayisini bulma yarisi yaris...',
    inviteLink: 'ODA OLUSTUR',
    joinRoom: 'ODAYA KATIL',
    waiting: 'Rakip araniyor...',
    roomCode: 'Oda Kodu:',
    share: 'PAYLAS',
    waitingOpponent: 'Rakip bekleniyor...',
  },
  setupScreen: {
    title: 'Gizli Sayini Sec!',
    subtitle: '4 Haneli Farkli Rakamlar Girin',
    confirm: 'ONAYLA',
    waiting: 'Rakip secim yapiyor...',
    opponentReady: 'Rakip hazir!',
    secretSaved: 'Sayin kaydedildi',
  },
  matchScreen: {
    title: 'Rakip Bulundu!',
    subtitle: 'Eslesme Yapiliyor...',
    you: 'SEN',
    opponent: 'RAKIP',
    ready: 'Hazir!',
  },
  gameScreen: {
    yourTurn: 'Senin Siran',
    opponentTurn: 'Rakip Dusunuyor...',
    active: 'Oyun Aktif',
    moves: 'Hamleler',
    yourGuess: 'Tahminin:',
    send: 'TAHMINI GONDER',
    round: 'Tur',
    bullHint: 'Bull: dogru rakam\ndogru yer',
    cowHint: 'Cow: dogru rakam\nyanlis yer',
    noGuess: 'Henuz tahmin yok',
    yourGuesses: 'Senin Tahminlerin',
    opponentGuesses: 'Rakibin Tahminleri',
  },
  resultScreen: {
    gameOver: 'OYUN BITTI!',
    youWon: 'KAZANDIN!',
    youLost: 'KAYBETTIN!',
    draw: 'BERABERE!',
    movesWin: 'Hamlede Bildin!',
    opponentSecret: 'Rakibin Sayisi:',
    yourMoves: 'Senin Hamlelerin:',
    opponentMoves: 'Rakip Hamleleri:',
    newGame: 'YENI OYUN',
    home: 'Ana Sayfa',
    waitingRematch: 'Rakip bekleniyor...',
    rematch: 'TEKRAR OYNA',
    accept: 'KABUL ET',
  },
  errors: {
    disconnected: 'Rakip ayrildi',
    connectionLost: 'Baglanti kesildi',
  },
};
